# Generated by Django 5.0.2 on 2024-05-01 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonesanitaire',
            name='code_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province'),
        ),
    ]
