# Generated by Django 5.0.2 on 2024-05-03 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_zonesanitaire_code_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AnalyseSanguine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('annee', models.IntegerField()),
                ('mois', models.CharField(max_length=20, null=True)),
                ('hemoglobine', models.FloatField()),
                ('albumine', models.FloatField()),
                ('azote_urique_sang', models.FloatField()),
                ('creatinine', models.FloatField()),
                ('uree_creatinine', models.FloatField()),
                ('fer_serique', models.FloatField()),
                ('ge', models.CharField(max_length=20, null=True)),
                ('code_aire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.airesanitaire')),
                ('code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enfant')),
            ],
        ),
        migrations.CreateModel(
            name='EtatInital',
            fields=[
                ('numero', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_prelevement', models.DateField()),
                ('annee', models.IntegerField()),
                ('mois', models.CharField(max_length=15)),
                ('poids', models.FloatField()),
                ('taille_en_cm', models.FloatField()),
                ('taille_en_m', models.FloatField()),
                ('z_score_pt', models.FloatField()),
                ('imc', models.FloatField()),
                ('z_score_imc_age', models.FloatField()),
                ('pa', models.FloatField()),
                ('pb', models.FloatField(default=0.0)),
                ('oedeme_nutri', models.CharField(choices=[('Yes', 'oui'), ('No', 'non')], max_length=5)),
                ('classification', models.CharField(max_length=20)),
                ('code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enfant')),
            ],
        ),
        migrations.CreateModel(
            name='Prelevement',
            fields=[
                ('qte_spiruline_recue', models.FloatField()),
                ('numero', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_prelevement', models.DateField()),
                ('annee', models.IntegerField()),
                ('mois', models.CharField(max_length=15)),
                ('poids', models.FloatField()),
                ('taille_en_cm', models.FloatField()),
                ('taille_en_m', models.FloatField()),
                ('z_score_pt', models.FloatField()),
                ('imc', models.FloatField()),
                ('z_score_imc_age', models.FloatField()),
                ('pa', models.FloatField()),
                ('pb', models.FloatField(default=0.0)),
                ('oedeme_nutri', models.CharField(choices=[('Yes', 'oui'), ('No', 'non')], max_length=5)),
                ('classification', models.CharField(max_length=20)),
                ('code_aire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.airesanitaire')),
                ('code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enfant')),
            ],
        ),
    ]
