# Generated by Django 5.0.2 on 2024-05-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_enfant_date_naissance_analysesanguine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysesanguine',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='etatinital',
            name='date_prelevement',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='etatinital',
            name='pb',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='etatinital',
            name='taille_en_cm',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prelevement',
            name='annee',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prelevement',
            name='date_prelevement',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prelevement',
            name='pb',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prelevement',
            name='taille_en_m',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prelevement',
            name='z_score_imc_age',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prelevement',
            name='z_score_pt',
            field=models.FloatField(null=True),
        ),
    ]
