# Generated by Django 5.0.2 on 2024-05-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_analysesanguine_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etatinital',
            name='taille_en_cm',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='prelevement',
            name='taille_en_m',
            field=models.FloatField(),
        ),
    ]
